#!/usr/bin/env bash
#
# Boots the merchant example with `signature_policy: strict` and checks that signature
# verification actually gates requests, end to end over HTTP.
#
# Separate from run-conformance.sh on purpose. The upstream suite sends
# `request-signature: test` and has no slot in `conformance_input.json` for a signing key,
# so it cannot produce a real RFC 9421 signature -- a strict run of the suite would refuse
# all 77 tests and prove only that strict refuses everything. Adding that slot is an
# upstream change; until it exists, this is the pass that covers the policy the default
# run never touches.
#
# The client signs with its own key and its own signature base (see
# tests/conformance/strict_signature_pass.py). Driving the SDK's signer against the SDK's
# verifier would reproduce the closed loop this whole lane exists to break.
#
set -euo pipefail

repo="$(cd "$(dirname "$0")/.." && pwd)"
cd "${repo}"

venv="${UCP_CONFORMANCE_VENV:-${repo}/var/conformance-venv}"
server_url="${SERVER_URL:-http://127.0.0.1:8091}"
state_dir="${UCP_MERCHANT_STATE_DIR:-${repo}/var/strict-signature-state}"
log_dir="${repo}/var/reports/conformance"
server_log="${log_dir}/merchant-strict.log"
python_bin="${PYTHON:-python3}"

mkdir -p "${log_dir}"

if [ ! -x "${venv}/bin/python" ]; then
    "${python_bin}" -m venv "${venv}"
fi
# The only dependency this pass needs. `cryptography` provides P-256 and DER decoding; the
# RFC 9421 base is assembled in the script, which is the point.
"${venv}/bin/pip" install --quiet --disable-pip-version-check cryptography

server_pid=''
cleanup() {
    if [ -n "${server_pid}" ]; then
        kill "${server_pid}" 2>/dev/null || true
        wait "${server_pid}" 2>/dev/null || true
    fi
}
trap cleanup EXIT

if [ -n "${UCP_STRICT_SKIP_SERVER:-}" ]; then
    # CI boots the merchant as its own compose service so the healthcheck gates the client.
    "${venv}/bin/python" tests/conformance/strict_signature_pass.py "${server_url}"
    exit $?
fi

rm -rf "${state_dir}" "${repo}/examples/merchant-symfony-app/var/cache"
mkdir -p "${state_dir}"

# Same shape as the default lane: prod, debug off, and profile-fetching development mode
# turned on explicitly because the agent profile this pass publishes is served over plain
# http on loopback, which the SDK refuses outside that mode -- correctly, since a profile
# carries the keys that verify every request from that platform.
export APP_ENV=prod
export APP_DEBUG=0
export UCP_MERCHANT_BASE_URI="${server_url}"
export UCP_MERCHANT_STATE_DIR="${state_dir}"
export UCP_PROFILE_FETCHING_DEV_MODE=1
export UCP_SIGNATURE_POLICY=strict

# The merchant needs its own key to publish `keys[]`; the agent's key is generated by the
# client. The state directory is wiped per run, so this is per run too.
php examples/merchant-symfony-app/bin/console ucp:signing-keys:generate >> "${server_log}" 2>&1

php -S "${server_url#http://}" \
    -t examples/merchant-symfony-app/public \
    examples/merchant-symfony-app/public/index.php \
    > "${server_log}" 2>&1 &
server_pid=$!

"${venv}/bin/python" - "${server_url}" <<'PY'
import sys, time, urllib.request, urllib.error
url = sys.argv[1].rstrip("/") + "/.well-known/ucp"
for _ in range(80):
    try:
        with urllib.request.urlopen(url, timeout=2) as response:
            if response.status == 200:
                print(f"merchant app answering at {url} with signature_policy=strict")
                sys.exit(0)
    except (urllib.error.URLError, OSError):
        pass
    time.sleep(0.2)
sys.exit("merchant app never answered at " + url)
PY

"${venv}/bin/python" tests/conformance/strict_signature_pass.py "${server_url}"
